services:
  postgres:
    image: postgres:15
    container_name: txlforma_db
    environment:
      POSTGRES_USER: ibtissam
      POSTGRES_PASSWORD: sae501
      POSTGRES_DB: txlforma
    ports:
      - "5432:5432"