services:
  postgres:
    image: postgres:15
    container_name: txlforma_db
    environment:
      POSTGRES_USER: txlforma
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: txlformadb
    ports:
      - "5432:5432"